language: go
go:
  - 1.9
  - 1.x
  - tip
os:
  - linux
  - osx
  - windows
matrix:
  allow_failures:
    - os: windows
      go: tip
install:
  - if [ "$TRAVIS_OS_NAME" = windows ]; then choco install -y make && which -a make; fi
  - make fetch
before_script:
  - mkdir -p "$GOPATH/src/github.com/shyiko" && ln -s "$GOPATH/src/github.com/kai2nenobu/jabba" "$GOPATH/src/github.com/shyiko/jabba"
script: make test
